# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.







pkgdatadir = $(datadir)/libuber
pkgincludedir = $(includedir)/libuber
pkglibdir = $(libdir)/libuber
pkglibexecdir = $(libexecdir)/libuber
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
noinst_PROGRAMS = demos/c/simple$(EXEEXT)
am__append_1 = src/Uber-1.0.gir
am__append_2 = $(gir_DATA) $(typelib_DATA)
am__append_3 = --enable-introspection
am__append_4 = introspection.m4
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/libuber.pc.in \
	$(top_srcdir)/configure $(top_srcdir)/src/config.h.in \
	$(uber_HEADERS) build/config.guess build/config.sub \
	build/depcomp build/install-sh build/ltmain.sh build/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/build/libtool.m4 \
	$(top_srcdir)/build/ltoptions.m4 \
	$(top_srcdir)/build/ltsugar.m4 \
	$(top_srcdir)/build/ltversion.m4 \
	$(top_srcdir)/build/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES = libuber.pc
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(girdir)" \
	"$(DESTDIR)$(typelibdir)" "$(DESTDIR)$(uberdir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
am__DEPENDENCIES_1 =
src_libuber_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
am__dirstamp = $(am__leading_dot)dirstamp
am_src_libuber_la_OBJECTS = src/src_libuber_la-uber-graph.lo \
	src/src_libuber_la-uber-frame-source.lo \
	src/src_libuber_la-uber-heat-map.lo \
	src/src_libuber_la-uber-line-graph.lo \
	src/src_libuber_la-uber-label.lo \
	src/src_libuber_la-uber-range.lo \
	src/src_libuber_la-uber-scale.lo \
	src/src_libuber_la-uber-scatter.lo \
	src/src_libuber_la-uber-timeout-interval.lo \
	src/src_libuber_la-uber-window.lo src/src_libuber_la-g-ring.lo
src_libuber_la_OBJECTS = $(am_src_libuber_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
src_libuber_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(src_libuber_la_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o \
	$@
PROGRAMS = $(noinst_PROGRAMS)
am_demos_c_simple_OBJECTS = demos/c/demos_c_simple-simple.$(OBJEXT)
demos_c_simple_OBJECTS = $(am_demos_c_simple_OBJECTS)
demos_c_simple_DEPENDENCIES = $(top_builddir)/src/libuber.la \
	$(am__DEPENDENCIES_1)
demos_c_simple_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(demos_c_simple_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o \
	$@
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/build/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(src_libuber_la_SOURCES) $(demos_c_simple_SOURCES)
DIST_SOURCES = $(src_libuber_la_SOURCES) $(demos_c_simple_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
DATA = $(gir_DATA) $(typelib_DATA)
HEADERS = $(uber_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
GZIP_ENV = --best
DIST_ARCHIVES = $(distdir).tar.bz2
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/stowers/Programming/uber-graph/build/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /home/stowers/Programming/uber-graph/build/missing --run autoconf
AUTOHEADER = ${SHELL} /home/stowers/Programming/uber-graph/build/missing --run autoheader
AUTOMAKE = ${SHELL} /home/stowers/Programming/uber-graph/build/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DEPS_CFLAGS = -pthread -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12  
DEPS_LIBS = -pthread -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0  
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTROSPECTION_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gobject-introspection-1.0  
INTROSPECTION_COMPILER = /usr/bin/g-ir-compiler
INTROSPECTION_GENERATE = /usr/bin/g-ir-generate
INTROSPECTION_GIRDIR = /usr/share/gir-1.0
INTROSPECTION_LIBS = -Wl,--export-dynamic -pthread -lgirepository-1.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lffi -lglib-2.0  
INTROSPECTION_MAKEFILE = /usr/share/gobject-introspection-1.0/Makefile.introspection
INTROSPECTION_SCANNER = /usr/bin/g-ir-scanner
INTROSPECTION_TYPELIBDIR = /usr/lib/girepository-1.0
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/stowers/Programming/uber-graph/build/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libuber
PACKAGE_BUGREPORT = 
PACKAGE_NAME = libuber
PACKAGE_STRING = libuber 0.0.1
PACKAGE_TARNAME = libuber
PACKAGE_URL = 
PACKAGE_VERSION = 0.0.1
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.0.1
abs_builddir = /home/stowers/Programming/uber-graph
abs_srcdir = /home/stowers/Programming/uber-graph
abs_top_builddir = /home/stowers/Programming/uber-graph
abs_top_srcdir = /home/stowers/Programming/uber-graph
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/stowers/Programming/uber-graph/build/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I build ${ACLOCAL_FLAGS}
SUBDIRS = .
DISTCHECK_CONFIGURE_FLAGS = --enable-introspection $(am__append_3)
MAINTAINERCLEANFILES = 
EXTRA_DIST = introspection.m4 $(am__append_4)
CLEANFILES = $(am__append_2)
lib_LTLIBRARIES = src/libuber.la
uberdir = $(pkgincludedir)/src
uber_HEADERS = \
	src/uber.h				\
	src/uber-graph.h		\
	src/uber-frame-source.h	\
	src/uber-heat-map.h		\
	src/uber-line-graph.h	\
	src/uber-label.h		\
	src/uber-range.h		\
	src/uber-scale.h		\
	src/uber-scatter.h		\
	src/uber-timeout-interval.h		\
	src/uber-window.h		\
	src/g-ring.h

src_libuber_la_SOURCES = \
	src/uber-graph.c		\
	src/uber-frame-source.c	\
	src/uber-heat-map.c		\
	src/uber-line-graph.c	\
	src/uber-label.c		\
	src/uber-range.c		\
	src/uber-scale.c		\
	src/uber-scatter.c		\
	src/uber-timeout-interval.c		\
	src/uber-window.c		\
	src/g-ring.c

src_libuber_la_CPPFLAGS = \
	-I$(top_srcdir)			\
	-I$(top_srcdir)/src		\
	$(AM_CPPFLAGS)

src_libuber_la_CFLAGS = \
	$(DEPS_CFLAGS)			\
	$(AM_CFLAGS)

src_libuber_la_LIBADD = \
	$(DEPS_LIBS)			\
	$(AM_LIBADD)

INTROSPECTION_GIRS = $(am__append_1)
INTROSPECTION_SCANNER_ARGS = --warn-all
INTROSPECTION_COMPILER_ARGS = 
src_Uber_1_0_gir_INCLUDES = Gtk-3.0
src_Uber_1_0_gir_CFLAGS = $(DEPS_CFLAGS) $(src_libuber_la_CPPFLAGS)
src_Uber_1_0_gir_LIBS = src/libuber.la
src_Uber_1_0_gir_FILES = $(src_libuber_la_SOURCES) $(uber_HEADERS)
src_Uber_1_0_gir_NAMESPACE = Uber
src_Uber_1_0_gir_EXPORT_PACKAGES = libuber
src_Uber_1_0_gir_SCANNERFLAGS = \
	--nsversion=1.0 		\
	--symbol-prefix=uber 	\
	--c-include="uber/uber.h"

girdir = $(datadir)/gir-1.0
gir_DATA = $(INTROSPECTION_GIRS)
typelibdir = $(libdir)/girepository-1.0
typelib_DATA = $(INTROSPECTION_GIRS:.gir=.typelib)
demos_c_simple_SOURCES = \
	demos/c/simple.c

demos_c_simple_CPPFLAGS = \
	-I$(top_srcdir)/ 	\
	-I$(top_srcdir)/src \
	$(AM_CPPFLAGS)

demos_c_simple_CFLAGS = \
	$(DEPS_CFLAGS) 		\
	$(AM_CFLAGS)

demos_c_simple_LDADD = \
	$(top_builddir)/src/libuber.la \
	$(DEPS_LIBS) 		\
	$(AM_LDADD)

all: all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

src/config.h: src/stamp-h1
	@if test ! -f $@; then rm -f src/stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) src/stamp-h1; else :; fi

src/stamp-h1: $(top_srcdir)/src/config.h.in $(top_builddir)/config.status
	@rm -f src/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/config.h
$(top_srcdir)/src/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f src/stamp-h1
	touch $@

distclean-hdr:
	-rm -f src/config.h src/stamp-h1
libuber.pc: $(top_builddir)/config.status $(srcdir)/libuber.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-graph.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-frame-source.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-heat-map.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-line-graph.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-label.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-range.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-scale.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-scatter.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-timeout-interval.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-uber-window.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/src_libuber_la-g-ring.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/libuber.la: $(src_libuber_la_OBJECTS) $(src_libuber_la_DEPENDENCIES) $(EXTRA_src_libuber_la_DEPENDENCIES) src/$(am__dirstamp)
	$(AM_V_CCLD)$(src_libuber_la_LINK) -rpath $(libdir) $(src_libuber_la_OBJECTS) $(src_libuber_la_LIBADD) $(LIBS)

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
demos/c/$(am__dirstamp):
	@$(MKDIR_P) demos/c
	@: > demos/c/$(am__dirstamp)
demos/c/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) demos/c/$(DEPDIR)
	@: > demos/c/$(DEPDIR)/$(am__dirstamp)
demos/c/demos_c_simple-simple.$(OBJEXT): demos/c/$(am__dirstamp) \
	demos/c/$(DEPDIR)/$(am__dirstamp)
demos/c/simple$(EXEEXT): $(demos_c_simple_OBJECTS) $(demos_c_simple_DEPENDENCIES) $(EXTRA_demos_c_simple_DEPENDENCIES) demos/c/$(am__dirstamp)
	@rm -f demos/c/simple$(EXEEXT)
	$(AM_V_CCLD)$(demos_c_simple_LINK) $(demos_c_simple_OBJECTS) $(demos_c_simple_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f demos/c/demos_c_simple-simple.$(OBJEXT)
	-rm -f src/src_libuber_la-g-ring.$(OBJEXT)
	-rm -f src/src_libuber_la-g-ring.lo
	-rm -f src/src_libuber_la-uber-frame-source.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-frame-source.lo
	-rm -f src/src_libuber_la-uber-graph.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-graph.lo
	-rm -f src/src_libuber_la-uber-heat-map.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-heat-map.lo
	-rm -f src/src_libuber_la-uber-label.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-label.lo
	-rm -f src/src_libuber_la-uber-line-graph.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-line-graph.lo
	-rm -f src/src_libuber_la-uber-range.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-range.lo
	-rm -f src/src_libuber_la-uber-scale.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-scale.lo
	-rm -f src/src_libuber_la-uber-scatter.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-scatter.lo
	-rm -f src/src_libuber_la-uber-timeout-interval.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-timeout-interval.lo
	-rm -f src/src_libuber_la-uber-window.$(OBJEXT)
	-rm -f src/src_libuber_la-uber-window.lo

distclean-compile:
	-rm -f *.tab.c

include demos/c/$(DEPDIR)/demos_c_simple-simple.Po
include src/$(DEPDIR)/src_libuber_la-g-ring.Plo
include src/$(DEPDIR)/src_libuber_la-uber-frame-source.Plo
include src/$(DEPDIR)/src_libuber_la-uber-graph.Plo
include src/$(DEPDIR)/src_libuber_la-uber-heat-map.Plo
include src/$(DEPDIR)/src_libuber_la-uber-label.Plo
include src/$(DEPDIR)/src_libuber_la-uber-line-graph.Plo
include src/$(DEPDIR)/src_libuber_la-uber-range.Plo
include src/$(DEPDIR)/src_libuber_la-uber-scale.Plo
include src/$(DEPDIR)/src_libuber_la-uber-scatter.Plo
include src/$(DEPDIR)/src_libuber_la-uber-timeout-interval.Plo
include src/$(DEPDIR)/src_libuber_la-uber-window.Plo

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

src/src_libuber_la-uber-graph.lo: src/uber-graph.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-graph.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-graph.Tpo -c -o src/src_libuber_la-uber-graph.lo `test -f 'src/uber-graph.c' || echo '$(srcdir)/'`src/uber-graph.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-graph.Tpo src/$(DEPDIR)/src_libuber_la-uber-graph.Plo
#	$(AM_V_CC)source='src/uber-graph.c' object='src/src_libuber_la-uber-graph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-graph.lo `test -f 'src/uber-graph.c' || echo '$(srcdir)/'`src/uber-graph.c

src/src_libuber_la-uber-frame-source.lo: src/uber-frame-source.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-frame-source.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-frame-source.Tpo -c -o src/src_libuber_la-uber-frame-source.lo `test -f 'src/uber-frame-source.c' || echo '$(srcdir)/'`src/uber-frame-source.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-frame-source.Tpo src/$(DEPDIR)/src_libuber_la-uber-frame-source.Plo
#	$(AM_V_CC)source='src/uber-frame-source.c' object='src/src_libuber_la-uber-frame-source.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-frame-source.lo `test -f 'src/uber-frame-source.c' || echo '$(srcdir)/'`src/uber-frame-source.c

src/src_libuber_la-uber-heat-map.lo: src/uber-heat-map.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-heat-map.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-heat-map.Tpo -c -o src/src_libuber_la-uber-heat-map.lo `test -f 'src/uber-heat-map.c' || echo '$(srcdir)/'`src/uber-heat-map.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-heat-map.Tpo src/$(DEPDIR)/src_libuber_la-uber-heat-map.Plo
#	$(AM_V_CC)source='src/uber-heat-map.c' object='src/src_libuber_la-uber-heat-map.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-heat-map.lo `test -f 'src/uber-heat-map.c' || echo '$(srcdir)/'`src/uber-heat-map.c

src/src_libuber_la-uber-line-graph.lo: src/uber-line-graph.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-line-graph.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-line-graph.Tpo -c -o src/src_libuber_la-uber-line-graph.lo `test -f 'src/uber-line-graph.c' || echo '$(srcdir)/'`src/uber-line-graph.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-line-graph.Tpo src/$(DEPDIR)/src_libuber_la-uber-line-graph.Plo
#	$(AM_V_CC)source='src/uber-line-graph.c' object='src/src_libuber_la-uber-line-graph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-line-graph.lo `test -f 'src/uber-line-graph.c' || echo '$(srcdir)/'`src/uber-line-graph.c

src/src_libuber_la-uber-label.lo: src/uber-label.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-label.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-label.Tpo -c -o src/src_libuber_la-uber-label.lo `test -f 'src/uber-label.c' || echo '$(srcdir)/'`src/uber-label.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-label.Tpo src/$(DEPDIR)/src_libuber_la-uber-label.Plo
#	$(AM_V_CC)source='src/uber-label.c' object='src/src_libuber_la-uber-label.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-label.lo `test -f 'src/uber-label.c' || echo '$(srcdir)/'`src/uber-label.c

src/src_libuber_la-uber-range.lo: src/uber-range.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-range.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-range.Tpo -c -o src/src_libuber_la-uber-range.lo `test -f 'src/uber-range.c' || echo '$(srcdir)/'`src/uber-range.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-range.Tpo src/$(DEPDIR)/src_libuber_la-uber-range.Plo
#	$(AM_V_CC)source='src/uber-range.c' object='src/src_libuber_la-uber-range.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-range.lo `test -f 'src/uber-range.c' || echo '$(srcdir)/'`src/uber-range.c

src/src_libuber_la-uber-scale.lo: src/uber-scale.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-scale.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-scale.Tpo -c -o src/src_libuber_la-uber-scale.lo `test -f 'src/uber-scale.c' || echo '$(srcdir)/'`src/uber-scale.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-scale.Tpo src/$(DEPDIR)/src_libuber_la-uber-scale.Plo
#	$(AM_V_CC)source='src/uber-scale.c' object='src/src_libuber_la-uber-scale.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-scale.lo `test -f 'src/uber-scale.c' || echo '$(srcdir)/'`src/uber-scale.c

src/src_libuber_la-uber-scatter.lo: src/uber-scatter.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-scatter.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-scatter.Tpo -c -o src/src_libuber_la-uber-scatter.lo `test -f 'src/uber-scatter.c' || echo '$(srcdir)/'`src/uber-scatter.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-scatter.Tpo src/$(DEPDIR)/src_libuber_la-uber-scatter.Plo
#	$(AM_V_CC)source='src/uber-scatter.c' object='src/src_libuber_la-uber-scatter.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-scatter.lo `test -f 'src/uber-scatter.c' || echo '$(srcdir)/'`src/uber-scatter.c

src/src_libuber_la-uber-timeout-interval.lo: src/uber-timeout-interval.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-timeout-interval.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-timeout-interval.Tpo -c -o src/src_libuber_la-uber-timeout-interval.lo `test -f 'src/uber-timeout-interval.c' || echo '$(srcdir)/'`src/uber-timeout-interval.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-timeout-interval.Tpo src/$(DEPDIR)/src_libuber_la-uber-timeout-interval.Plo
#	$(AM_V_CC)source='src/uber-timeout-interval.c' object='src/src_libuber_la-uber-timeout-interval.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-timeout-interval.lo `test -f 'src/uber-timeout-interval.c' || echo '$(srcdir)/'`src/uber-timeout-interval.c

src/src_libuber_la-uber-window.lo: src/uber-window.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-uber-window.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-uber-window.Tpo -c -o src/src_libuber_la-uber-window.lo `test -f 'src/uber-window.c' || echo '$(srcdir)/'`src/uber-window.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-uber-window.Tpo src/$(DEPDIR)/src_libuber_la-uber-window.Plo
#	$(AM_V_CC)source='src/uber-window.c' object='src/src_libuber_la-uber-window.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-uber-window.lo `test -f 'src/uber-window.c' || echo '$(srcdir)/'`src/uber-window.c

src/src_libuber_la-g-ring.lo: src/g-ring.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -MT src/src_libuber_la-g-ring.lo -MD -MP -MF src/$(DEPDIR)/src_libuber_la-g-ring.Tpo -c -o src/src_libuber_la-g-ring.lo `test -f 'src/g-ring.c' || echo '$(srcdir)/'`src/g-ring.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/src_libuber_la-g-ring.Tpo src/$(DEPDIR)/src_libuber_la-g-ring.Plo
#	$(AM_V_CC)source='src/g-ring.c' object='src/src_libuber_la-g-ring.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_libuber_la_CPPFLAGS) $(CPPFLAGS) $(src_libuber_la_CFLAGS) $(CFLAGS) -c -o src/src_libuber_la-g-ring.lo `test -f 'src/g-ring.c' || echo '$(srcdir)/'`src/g-ring.c

demos/c/demos_c_simple-simple.o: demos/c/simple.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(demos_c_simple_CPPFLAGS) $(CPPFLAGS) $(demos_c_simple_CFLAGS) $(CFLAGS) -MT demos/c/demos_c_simple-simple.o -MD -MP -MF demos/c/$(DEPDIR)/demos_c_simple-simple.Tpo -c -o demos/c/demos_c_simple-simple.o `test -f 'demos/c/simple.c' || echo '$(srcdir)/'`demos/c/simple.c
	$(AM_V_at)$(am__mv) demos/c/$(DEPDIR)/demos_c_simple-simple.Tpo demos/c/$(DEPDIR)/demos_c_simple-simple.Po
#	$(AM_V_CC)source='demos/c/simple.c' object='demos/c/demos_c_simple-simple.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(demos_c_simple_CPPFLAGS) $(CPPFLAGS) $(demos_c_simple_CFLAGS) $(CFLAGS) -c -o demos/c/demos_c_simple-simple.o `test -f 'demos/c/simple.c' || echo '$(srcdir)/'`demos/c/simple.c

demos/c/demos_c_simple-simple.obj: demos/c/simple.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(demos_c_simple_CPPFLAGS) $(CPPFLAGS) $(demos_c_simple_CFLAGS) $(CFLAGS) -MT demos/c/demos_c_simple-simple.obj -MD -MP -MF demos/c/$(DEPDIR)/demos_c_simple-simple.Tpo -c -o demos/c/demos_c_simple-simple.obj `if test -f 'demos/c/simple.c'; then $(CYGPATH_W) 'demos/c/simple.c'; else $(CYGPATH_W) '$(srcdir)/demos/c/simple.c'; fi`
	$(AM_V_at)$(am__mv) demos/c/$(DEPDIR)/demos_c_simple-simple.Tpo demos/c/$(DEPDIR)/demos_c_simple-simple.Po
#	$(AM_V_CC)source='demos/c/simple.c' object='demos/c/demos_c_simple-simple.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(demos_c_simple_CPPFLAGS) $(CPPFLAGS) $(demos_c_simple_CFLAGS) $(CFLAGS) -c -o demos/c/demos_c_simple-simple.obj `if test -f 'demos/c/simple.c'; then $(CYGPATH_W) 'demos/c/simple.c'; else $(CYGPATH_W) '$(srcdir)/demos/c/simple.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf demos/c/.libs demos/c/_libs
	-rm -rf src/.libs src/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-girDATA: $(gir_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(girdir)" || $(MKDIR_P) "$(DESTDIR)$(girdir)"
	@list='$(gir_DATA)'; test -n "$(girdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(girdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(girdir)" || exit $$?; \
	done

uninstall-girDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(gir_DATA)'; test -n "$(girdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(girdir)'; $(am__uninstall_files_from_dir)
install-typelibDATA: $(typelib_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(typelibdir)" || $(MKDIR_P) "$(DESTDIR)$(typelibdir)"
	@list='$(typelib_DATA)'; test -n "$(typelibdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(typelibdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(typelibdir)" || exit $$?; \
	done

uninstall-typelibDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(typelib_DATA)'; test -n "$(typelibdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(typelibdir)'; $(am__uninstall_files_from_dir)
install-uberHEADERS: $(uber_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(uberdir)" || $(MKDIR_P) "$(DESTDIR)$(uberdir)"
	@list='$(uber_HEADERS)'; test -n "$(uberdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(uberdir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(uberdir)" || exit $$?; \
	done

uninstall-uberHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(uber_HEADERS)'; test -n "$(uberdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(uberdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(girdir)" "$(DESTDIR)$(typelibdir)" "$(DESTDIR)$(uberdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f demos/c/$(DEPDIR)/$(am__dirstamp)
	-rm -f demos/c/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf demos/c/$(DEPDIR) src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-girDATA install-typelibDATA \
	install-uberHEADERS

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf demos/c/$(DEPDIR) src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-girDATA uninstall-libLTLIBRARIES \
	uninstall-typelibDATA uninstall-uberHEADERS

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-noinstPROGRAMS ctags \
	ctags-recursive dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-lzma dist-shar dist-tarZ dist-xz dist-zip distcheck \
	distclean distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-girDATA \
	install-html install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip install-typelibDATA \
	install-uberHEADERS installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-girDATA \
	uninstall-libLTLIBRARIES uninstall-typelibDATA \
	uninstall-uberHEADERS


# Introspection
-include $(INTROSPECTION_MAKEFILE)

src/Uber-1.0.gir: src/libuber.la

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
